# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import taskingai
from taskingai.models.base_success_empty_out_schema import BaseSuccessEmptyOutSchema  # noqa: E501
from taskingai.rest import ApiException


class TestBaseSuccessEmptyOutSchema(unittest.TestCase):
    """BaseSuccessEmptyOutSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseSuccessEmptyOutSchema(self):
        """Test BaseSuccessEmptyOutSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = taskingai.models.base_success_empty_out_schema.BaseSuccessEmptyOutSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
