# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import taskingai
from taskingai.models.assistant_create_request_body_schema import AssistantCreateRequestBodySchema  # noqa: E501
from taskingai.rest import ApiException


class TestAssistantCreateRequestBodySchema(unittest.TestCase):
    """AssistantCreateRequestBodySchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssistantCreateRequestBodySchema(self):
        """Test AssistantCreateRequestBodySchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = taskingai.models.assistant_create_request_body_schema.AssistantCreateRequestBodySchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
