# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import taskingai
from taskingai.models.chunk_query_response_schema import ChunkQueryResponseSchema  # noqa: E501
from taskingai.rest import ApiException


class TestChunkQueryResponseSchema(unittest.TestCase):
    """ChunkQueryResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChunkQueryResponseSchema(self):
        """Test ChunkQueryResponseSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = taskingai.models.chunk_query_response_schema.ChunkQueryResponseSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
