# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import taskingai
from taskingai.api.retrieval_api import RetrievalApi  # noqa: E501
from taskingai.rest import ApiException


class TestRetrievalApi(unittest.TestCase):
    """RetrievalApi unit test stubs"""

    def setUp(self):
        self.api = RetrievalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_collection(self):
        """Test case for create_collection

        Create collection  # noqa: E501
        """
        pass

    def test_create_record(self):
        """Test case for create_record

        Create record  # noqa: E501
        """
        pass

    def test_delete_collection(self):
        """Test case for delete_collection

        Delete collection  # noqa: E501
        """
        pass

    def test_delete_record(self):
        """Test case for delete_record

        Delete record  # noqa: E501
        """
        pass

    def test_get_collection(self):
        """Test case for get_collection

        Get collection  # noqa: E501
        """
        pass

    def test_get_record(self):
        """Test case for get_record

        Get record  # noqa: E501
        """
        pass

    def test_list_collections(self):
        """Test case for list_collections

        List collections  # noqa: E501
        """
        pass

    def test_list_records(self):
        """Test case for list_records

        List records  # noqa: E501
        """
        pass

    def test_query_chunks(self):
        """Test case for query_chunks

        Query chunks  # noqa: E501
        """
        pass

    def test_update_collection(self):
        """Test case for update_collection

        Update collection  # noqa: E501
        """
        pass

    def test_update_record(self):
        """Test case for update_record

        Update record  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
