# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import taskingai
from taskingai.models.chat_update_request_body_schema import ChatUpdateRequestBodySchema  # noqa: E501
from taskingai.rest import ApiException


class TestChatUpdateRequestBodySchema(unittest.TestCase):
    """ChatUpdateRequestBodySchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChatUpdateRequestBodySchema(self):
        """Test ChatUpdateRequestBodySchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = taskingai.models.chat_update_request_body_schema.ChatUpdateRequestBodySchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
