# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatGenerateRequestBodySchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stream': 'object',
        'message': 'ChatGenerateUserMessage',
        'system_prompt_variables': 'object'
    }

    attribute_map = {
        'stream': 'stream',
        'message': 'message',
        'system_prompt_variables': 'system_prompt_variables'
    }

    def __init__(self, stream=None, message=None, system_prompt_variables=None):  # noqa: E501
        """ChatGenerateRequestBodySchema - a model defined in Swagger"""  # noqa: E501
        self._stream = None
        self._message = None
        self._system_prompt_variables = None
        self.discriminator = None
        if stream is not None:
            self.stream = stream
        self.message = message
        if system_prompt_variables is not None:
            self.system_prompt_variables = system_prompt_variables

    @property
    def stream(self):
        """Gets the stream of this ChatGenerateRequestBodySchema.  # noqa: E501


        :return: The stream of this ChatGenerateRequestBodySchema.  # noqa: E501
        :rtype: object
        """
        return self._stream

    @stream.setter
    def stream(self, stream):
        """Sets the stream of this ChatGenerateRequestBodySchema.


        :param stream: The stream of this ChatGenerateRequestBodySchema.  # noqa: E501
        :type: object
        """

        self._stream = stream

    @property
    def message(self):
        """Gets the message of this ChatGenerateRequestBodySchema.  # noqa: E501


        :return: The message of this ChatGenerateRequestBodySchema.  # noqa: E501
        :rtype: ChatGenerateUserMessage
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ChatGenerateRequestBodySchema.


        :param message: The message of this ChatGenerateRequestBodySchema.  # noqa: E501
        :type: ChatGenerateUserMessage
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def system_prompt_variables(self):
        """Gets the system_prompt_variables of this ChatGenerateRequestBodySchema.  # noqa: E501


        :return: The system_prompt_variables of this ChatGenerateRequestBodySchema.  # noqa: E501
        :rtype: object
        """
        return self._system_prompt_variables

    @system_prompt_variables.setter
    def system_prompt_variables(self, system_prompt_variables):
        """Sets the system_prompt_variables of this ChatGenerateRequestBodySchema.


        :param system_prompt_variables: The system_prompt_variables of this ChatGenerateRequestBodySchema.  # noqa: E501
        :type: object
        """

        self._system_prompt_variables = system_prompt_variables

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatGenerateRequestBodySchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatGenerateRequestBodySchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
