# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CollectionCreateRequestBodySchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'capacity': 'object',
        'name': 'object',
        'description': 'object',
        'chunk_size': 'object',
        'embedding_model_id': 'object',
        'metadata': 'object'
    }

    attribute_map = {
        'capacity': 'capacity',
        'name': 'name',
        'description': 'description',
        'chunk_size': 'chunk_size',
        'embedding_model_id': 'embedding_model_id',
        'metadata': 'metadata'
    }

    def __init__(self, capacity=None, name=None, description=None, chunk_size=None, embedding_model_id=None, metadata=None):  # noqa: E501
        """CollectionCreateRequestBodySchema - a model defined in Swagger"""  # noqa: E501
        self._capacity = None
        self._name = None
        self._description = None
        self._chunk_size = None
        self._embedding_model_id = None
        self._metadata = None
        self.discriminator = None
        if capacity is not None:
            self.capacity = capacity
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if chunk_size is not None:
            self.chunk_size = chunk_size
        self.embedding_model_id = embedding_model_id
        if metadata is not None:
            self.metadata = metadata

    @property
    def capacity(self):
        """Gets the capacity of this CollectionCreateRequestBodySchema.  # noqa: E501


        :return: The capacity of this CollectionCreateRequestBodySchema.  # noqa: E501
        :rtype: object
        """
        return self._capacity

    @capacity.setter
    def capacity(self, capacity):
        """Sets the capacity of this CollectionCreateRequestBodySchema.


        :param capacity: The capacity of this CollectionCreateRequestBodySchema.  # noqa: E501
        :type: object
        """

        self._capacity = capacity

    @property
    def name(self):
        """Gets the name of this CollectionCreateRequestBodySchema.  # noqa: E501


        :return: The name of this CollectionCreateRequestBodySchema.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CollectionCreateRequestBodySchema.


        :param name: The name of this CollectionCreateRequestBodySchema.  # noqa: E501
        :type: object
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this CollectionCreateRequestBodySchema.  # noqa: E501


        :return: The description of this CollectionCreateRequestBodySchema.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CollectionCreateRequestBodySchema.


        :param description: The description of this CollectionCreateRequestBodySchema.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def chunk_size(self):
        """Gets the chunk_size of this CollectionCreateRequestBodySchema.  # noqa: E501


        :return: The chunk_size of this CollectionCreateRequestBodySchema.  # noqa: E501
        :rtype: object
        """
        return self._chunk_size

    @chunk_size.setter
    def chunk_size(self, chunk_size):
        """Sets the chunk_size of this CollectionCreateRequestBodySchema.


        :param chunk_size: The chunk_size of this CollectionCreateRequestBodySchema.  # noqa: E501
        :type: object
        """

        self._chunk_size = chunk_size

    @property
    def embedding_model_id(self):
        """Gets the embedding_model_id of this CollectionCreateRequestBodySchema.  # noqa: E501


        :return: The embedding_model_id of this CollectionCreateRequestBodySchema.  # noqa: E501
        :rtype: object
        """
        return self._embedding_model_id

    @embedding_model_id.setter
    def embedding_model_id(self, embedding_model_id):
        """Sets the embedding_model_id of this CollectionCreateRequestBodySchema.


        :param embedding_model_id: The embedding_model_id of this CollectionCreateRequestBodySchema.  # noqa: E501
        :type: object
        """
        if embedding_model_id is None:
            raise ValueError("Invalid value for `embedding_model_id`, must not be `None`")  # noqa: E501

        self._embedding_model_id = embedding_model_id

    @property
    def metadata(self):
        """Gets the metadata of this CollectionCreateRequestBodySchema.  # noqa: E501


        :return: The metadata of this CollectionCreateRequestBodySchema.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this CollectionCreateRequestBodySchema.


        :param metadata: The metadata of this CollectionCreateRequestBodySchema.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CollectionCreateRequestBodySchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollectionCreateRequestBodySchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
