# coding: utf-8

"""
    TaskingAI API

    OpenAPI spec version: 0.1.0
"""

import pprint
import re  # noqa: F401

import six

class RecordCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'object',
        'text': 'object',
        'metadata': 'object'
    }

    attribute_map = {
        'type': 'type',
        'text': 'text',
        'metadata': 'metadata'
    }

    def __init__(self, type=None, text=None, metadata=None):  # noqa: E501
        """RecordCreateRequest - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._text = None
        self._metadata = None
        self.discriminator = None
        self.type = type
        if text is not None:
            self.text = text
        if metadata is not None:
            self.metadata = metadata

    @property
    def type(self):
        """Gets the type of this RecordCreateRequest.  # noqa: E501

        The record type, which can be `text` or `file`.  # noqa: E501

        :return: The type of this RecordCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RecordCreateRequest.

        The record type, which can be `text` or `file`.  # noqa: E501

        :param type: The type of this RecordCreateRequest.  # noqa: E501
        :type: object
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def text(self):
        """Gets the text of this RecordCreateRequest.  # noqa: E501

        The record text. It's only valid when the record type is `text`.  # noqa: E501

        :return: The text of this RecordCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this RecordCreateRequest.

        The record text. It's only valid when the record type is `text`.  # noqa: E501

        :param text: The text of this RecordCreateRequest.  # noqa: E501
        :type: object
        """

        self._text = text

    @property
    def metadata(self):
        """Gets the metadata of this RecordCreateRequest.  # noqa: E501

        The record metadata. It can store up to 16 key-value pairs where each key's length is less than 64 and value's length is less than 512.  # noqa: E501

        :return: The metadata of this RecordCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this RecordCreateRequest.

        The record metadata. It can store up to 16 key-value pairs where each key's length is less than 64 and value's length is less than 512.  # noqa: E501

        :param metadata: The metadata of this RecordCreateRequest.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecordCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecordCreateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
