# coding: utf-8

# flake8: noqa
"""
    TaskingAI API

    OpenAPI spec version: 0.1.0
"""

from __future__ import absolute_import

# import models into model package
from taskingai.client.models.action import Action
from taskingai.client.models.action_authentication import ActionAuthentication
from taskingai.client.models.action_authentication_type import ActionAuthenticationType
from taskingai.client.models.action_bulk_create_request import ActionBulkCreateRequest
from taskingai.client.models.action_bulk_create_response import ActionBulkCreateResponse
from taskingai.client.models.action_delete_response import ActionDeleteResponse
from taskingai.client.models.action_get_response import ActionGetResponse
from taskingai.client.models.action_list_response import ActionListResponse
from taskingai.client.models.action_run_request import ActionRunRequest
from taskingai.client.models.action_run_response import ActionRunResponse
from taskingai.client.models.action_update_request import ActionUpdateRequest
from taskingai.client.models.action_update_response import ActionUpdateResponse
from taskingai.client.models.assistant import Assistant
from taskingai.client.models.assistant_create_request import AssistantCreateRequest
from taskingai.client.models.assistant_create_response import AssistantCreateResponse
from taskingai.client.models.assistant_delete_response import AssistantDeleteResponse
from taskingai.client.models.assistant_get_response import AssistantGetResponse
from taskingai.client.models.assistant_list_response import AssistantListResponse
from taskingai.client.models.assistant_retrieval import AssistantRetrieval
from taskingai.client.models.assistant_tool import AssistantTool
from taskingai.client.models.assistant_update_request import AssistantUpdateRequest
from taskingai.client.models.assistant_update_response import AssistantUpdateResponse
from taskingai.client.models.chat import Chat
from taskingai.client.models.chat_completion_response import ChatCompletionResponse
from taskingai.client.models.chat_completion import ChatCompletion
from taskingai.client.models.chat_completion_assistant_message import ChatCompletionAssistantMessage
from taskingai.client.models.chat_completion_function import ChatCompletionFunction
from taskingai.client.models.chat_completion_function_call import ChatCompletionFunctionCall
from taskingai.client.models.chat_completion_function_message import ChatCompletionFunctionMessage
from taskingai.client.models.chat_completion_request import ChatCompletionRequest
from taskingai.client.models.chat_completion_role import ChatCompletionRole
from taskingai.client.models.chat_completion_system_message import ChatCompletionSystemMessage
from taskingai.client.models.chat_completion_user_message import ChatCompletionUserMessage
from taskingai.client.models.chat_create_request import ChatCreateRequest
from taskingai.client.models.chat_create_response import ChatCreateResponse
from taskingai.client.models.chat_delete_response import ChatDeleteResponse
from taskingai.client.models.chat_get_response import ChatGetResponse
from taskingai.client.models.chat_list_response import ChatListResponse
from taskingai.client.models.chat_update_request import ChatUpdateRequest
from taskingai.client.models.chat_update_response import ChatUpdateResponse
from taskingai.client.models.chunk import Chunk
from taskingai.client.models.chunk_query_request import ChunkQueryRequest
from taskingai.client.models.chunk_query_response import ChunkQueryResponse
from taskingai.client.models.collection import Collection
from taskingai.client.models.collection_config import CollectionConfig
from taskingai.client.models.collection_create_request import CollectionCreateRequest
from taskingai.client.models.collection_create_response import CollectionCreateResponse
from taskingai.client.models.collection_get_response import CollectionGetResponse
from taskingai.client.models.collection_list_response import CollectionListResponse
from taskingai.client.models.collection_update_request import CollectionUpdateRequest
from taskingai.client.models.collection_update_response import CollectionUpdateResponse
from taskingai.client.models.delete_collection_response import DeleteCollectionResponse
from taskingai.client.models.function import Function
from taskingai.client.models.function_create_request import FunctionCreateRequest
from taskingai.client.models.function_create_response import FunctionCreateResponse
from taskingai.client.models.function_delete_response import FunctionDeleteResponse
from taskingai.client.models.function_get_response import FunctionGetResponse
from taskingai.client.models.function_list_response import FunctionListResponse
from taskingai.client.models.function_update_request import FunctionUpdateRequest
from taskingai.client.models.function_update_response import FunctionUpdateResponse
from taskingai.client.models.http_validation_error import HTTPValidationError
from taskingai.client.models.message import Message
from taskingai.client.models.message_content import MessageContent
from taskingai.client.models.message_create_request import MessageCreateRequest
from taskingai.client.models.message_create_response import MessageCreateResponse
from taskingai.client.models.message_generate_request import MessageGenerateRequest
from taskingai.client.models.message_generate_response import MessageGenerateResponse
from taskingai.client.models.message_generation_response_option import MessageGenerationResponseOption
from taskingai.client.models.message_get_response import MessageGetResponse
from taskingai.client.models.message_list_response import MessageListResponse
from taskingai.client.models.message_role import MessageRole
from taskingai.client.models.message_update_request import MessageUpdateRequest
from taskingai.client.models.message_update_response import MessageUpdateResponse
from taskingai.client.models.parameters_input import ParametersInput
from taskingai.client.models.parameters_output import ParametersOutput
from taskingai.client.models.record import Record
from taskingai.client.models.record_create_request import RecordCreateRequest
from taskingai.client.models.record_create_response import RecordCreateResponse
from taskingai.client.models.record_delete_response import RecordDeleteResponse
from taskingai.client.models.record_get_response import RecordGetResponse
from taskingai.client.models.record_list_response import RecordListResponse
from taskingai.client.models.record_update_request import RecordUpdateRequest
from taskingai.client.models.record_update_response import RecordUpdateResponse
from taskingai.client.models.text_embedding_output import TextEmbeddingOutput
from taskingai.client.models.text_embedding_request import TextEmbeddingRequest
from taskingai.client.models.text_embedding_response import TextEmbeddingResponse
from taskingai.client.models.validation_error import ValidationError
