# coding: utf-8

"""
    TaskingAI API

    OpenAPI spec version: 0.1.0
"""

import pprint
import re  # noqa: F401

import six

class ActionAuthenticationOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'ActionAuthenticationType',
        'secret': 'object',
        'content': 'object'
    }

    attribute_map = {
        'type': 'type',
        'secret': 'secret',
        'content': 'content'
    }

    def __init__(self, type=None, secret=None, content=None):  # noqa: E501
        """ActionAuthenticationOutput - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._secret = None
        self._content = None
        self.discriminator = None
        self.type = type
        self.secret = secret
        self.content = content

    @property
    def type(self):
        """Gets the type of this ActionAuthenticationOutput.  # noqa: E501


        :return: The type of this ActionAuthenticationOutput.  # noqa: E501
        :rtype: ActionAuthenticationType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ActionAuthenticationOutput.


        :param type: The type of this ActionAuthenticationOutput.  # noqa: E501
        :type: ActionAuthenticationType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def secret(self):
        """Gets the secret of this ActionAuthenticationOutput.  # noqa: E501


        :return: The secret of this ActionAuthenticationOutput.  # noqa: E501
        :rtype: object
        """
        return self._secret

    @secret.setter
    def secret(self, secret):
        """Sets the secret of this ActionAuthenticationOutput.


        :param secret: The secret of this ActionAuthenticationOutput.  # noqa: E501
        :type: object
        """
        if secret is None:
            raise ValueError("Invalid value for `secret`, must not be `None`")  # noqa: E501

        self._secret = secret

    @property
    def content(self):
        """Gets the content of this ActionAuthenticationOutput.  # noqa: E501


        :return: The content of this ActionAuthenticationOutput.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ActionAuthenticationOutput.


        :param content: The content of this ActionAuthenticationOutput.  # noqa: E501
        :type: object
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionAuthenticationOutput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionAuthenticationOutput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
