# coding: utf-8

"""
    TaskingAI API

    OpenAPI spec version: 0.1.0
"""

import pprint
import re  # noqa: F401

import six

class ChatCompletionFunctionMessage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'object',
        'role': 'object',
        'name': 'object'
    }

    attribute_map = {
        'content': 'content',
        'role': 'role',
        'name': 'name'
    }

    def __init__(self, content=None, role=None, name=None):  # noqa: E501
        """ChatCompletionFunctionMessage - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._role = None
        self._name = None
        self.discriminator = None
        if content is not None:
            self.content = content
        if role is not None:
            self.role = role
        self.name = name

    @property
    def content(self):
        """Gets the content of this ChatCompletionFunctionMessage.  # noqa: E501

        The content of the message.  # noqa: E501

        :return: The content of this ChatCompletionFunctionMessage.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ChatCompletionFunctionMessage.

        The content of the message.  # noqa: E501

        :param content: The content of this ChatCompletionFunctionMessage.  # noqa: E501
        :type: object
        """

        self._content = content

    @property
    def role(self):
        """Gets the role of this ChatCompletionFunctionMessage.  # noqa: E501

        The role of the message, which is always 'function' for a function message  # noqa: E501

        :return: The role of this ChatCompletionFunctionMessage.  # noqa: E501
        :rtype: object
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this ChatCompletionFunctionMessage.

        The role of the message, which is always 'function' for a function message  # noqa: E501

        :param role: The role of this ChatCompletionFunctionMessage.  # noqa: E501
        :type: object
        """

        self._role = role

    @property
    def name(self):
        """Gets the name of this ChatCompletionFunctionMessage.  # noqa: E501

        The name of the function.  # noqa: E501

        :return: The name of this ChatCompletionFunctionMessage.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ChatCompletionFunctionMessage.

        The name of the function.  # noqa: E501

        :param name: The name of this ChatCompletionFunctionMessage.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatCompletionFunctionMessage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatCompletionFunctionMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
