# coding: utf-8

"""
    TaskingAI API

    OpenAPI spec version: 0.1.0
"""

import pprint
import re  # noqa: F401

import six

class MessageCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'role': 'object',
        'content': 'object',
        'metadata': 'object'
    }

    attribute_map = {
        'role': 'role',
        'content': 'content',
        'metadata': 'metadata'
    }

    def __init__(self, role=None, content=None, metadata=None):  # noqa: E501
        """MessageCreateRequest - a model defined in Swagger"""  # noqa: E501
        self._role = None
        self._content = None
        self._metadata = None
        self.discriminator = None
        self.role = role
        self.content = content
        if metadata is not None:
            self.metadata = metadata

    @property
    def role(self):
        """Gets the role of this MessageCreateRequest.  # noqa: E501

        The role of the message. Currently only `user` is supported.  # noqa: E501

        :return: The role of this MessageCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this MessageCreateRequest.

        The role of the message. Currently only `user` is supported.  # noqa: E501

        :param role: The role of this MessageCreateRequest.  # noqa: E501
        :type: object
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def content(self):
        """Gets the content of this MessageCreateRequest.  # noqa: E501

        The message content.  # noqa: E501

        :return: The content of this MessageCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this MessageCreateRequest.

        The message content.  # noqa: E501

        :param content: The content of this MessageCreateRequest.  # noqa: E501
        :type: object
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def metadata(self):
        """Gets the metadata of this MessageCreateRequest.  # noqa: E501

        The message metadata. It can store up to 16 key-value pairs where each key's length is less than 64 and value's length is less than 512.  # noqa: E501

        :return: The metadata of this MessageCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this MessageCreateRequest.

        The message metadata. It can store up to 16 key-value pairs where each key's length is less than 64 and value's length is less than 512.  # noqa: E501

        :param metadata: The metadata of this MessageCreateRequest.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessageCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessageCreateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
